name: FastAPI Test Deployment

on:
  push:
    branches:
      - feature/ai-cicd

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST_TEST }}
          username: ${{ secrets.EC2_USER_TEST }}
          key: ${{ secrets.EC2_SSH_KEY_TEST }}
          port: 22
          script: |
            # 도커 로그인
            docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_PASSWORD }}
            
            # 최신 이미지 풀
            docker pull ${{ secrets.DOCKER_REPO }}:test
            
            # 기존 컨테이너 중지 및 제거
            docker stop fastapi-app-test || true
            docker rm fastapi-app-test || true
            
            # 새 컨테이너 실행
            docker run -d \
              --name fastapi-app-test \
              -p 8000:8000 \
              -e GH_TOKEN='${{ secrets.GH_TOKEN }}' \
              -e OPENAI_API_KEY='${{ secrets.OPENAI_API_KEY }}' \
              -e HOST='${{ secrets.HOST }}' \
              -e PORT='${{ secrets.PORT }}' \
              --restart unless-stopped \
              ${{ secrets.DOCKER_REPO }}:test